### ISSUE TITLE
Parts of Positron's Lake Michigan’s turns white depending on zooming

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/CartoDB-basemaps#66]
A user has detected a strange behaviour within the Positron basemap. In zoom levels 7 and 8 parts of Lake Michigan turns white.

![lake1](https://cloud.githubusercontent.com/assets/5215798/14422353/b4864972-ffd6-11e5-9875-2384150e07cc.png)

![lake2](https://cloud.githubusercontent.com/assets/5215798/14422355/b63a2b4e-ffd6-11e5-93ba-f9ffad31ca7a.png)

**Comment by pnorman** [comment]
This is probably a case of the great lakes are not rendering, but only on some servers

* The Great Lakes are coming from water multipolygons now as opposed to coastline data in OSM
* The water queries are complex and confusing
* The global false background is land, so it's a case of missing water instead of excess land
* The water is coming from `#land_negative` where `is_lake=1`
```sql
(SELECT
    id::bigint,
    the_geom_webmercator,
    name,
    type,
    is_lake,
    ne_scalerank,
    area
  FROM water_zoomed('!scale_denominator!', !bbox!) AS _)
UNION ALL
(SELECT
    cartodb_id::bigint,
    the_geom_webmercator,
    '' AS name,
    'ocean' AS type,
    1 AS is_lake,
    0 AS ne_scalerank,
    999999999 AS area
  FROM land_negative_zoomed('!scale_denominator!', !bbox!) AS _)
```
* `land_negative_zoomed` only kicks in at z9
* on z7 `water_zoomed` is
```sql
(SELECT
    cartodb_id::bigint AS id,
    the_geom_webmercator,
    name::text,
    ''river'' AS type,
    0 AS is_lake,
    scalerank::integer,
    ST_Area(the_geom_webmercator)::bigint
  FROM ne_10m_rivers_lake_centerlines
  WHERE the_geom_webmercator && $1)
UNION 
(SELECT
    cartodb_id::bigint AS id,
    the_geom_webmercator,
    name,
    ''lake'' AS type,
    1 AS is_lake,
    scalerank::integer,
    ST_Area(the_geom_webmercator)::bigint
  FROM ne_10m_lakes
  WHERE the_geom_webmercator && $1)
  ORDER BY is_lake ASC
```
* on z8 `water_zoomed` is
```sql
SELECT id::bigint AS id, the_geom_webmercator, name::text, type::text,
    (CASE 
      WHEN type IN (''water'',''bay'',''riverbank'',''reservoir'') 
        AND ST_GeometryType(the_geom_webmercator) IN (''ST_Polygon'',''ST_MultiPolygon'') THEN 1 
      ELSE 0 
    END) as is_lake,
    0 as ne_scalerank,
    area::bigint
  FROM water_areas_z10
  WHERE the_geom_webmercator && $1
  ORDER BY is_lake ASC
```
* `water_areas_z10` is a mat view, and is effectively
```sql
SELECT
    tags->'name' AS name,
    ST_Area(the_geom)::bigint AS area,
    COALESCE(tags -> 'natural', tags -> 'waterway', tags -> 'landuse') AS type,
    generalize(generalize(the_geom ,13),10) AS the_geom_webmercator
  FROM planet
  WHERE ST_Area(the_geom)::bigint > 25000 OR COALESCE(tags -> 'natural', tags -> 'waterway', tags -> 'landuse') = 'riverbank'
    AND (tags -> 'natural' IN ('water','bay')
      OR tags -> 'waterway' IN ('riverbank','canal','river')
      OR tags -> 'landuse' IN ('reservoir'))
```
* On z8 it looks like a problem with one of the three mat view refreshes or `planet`, and on z7 it looks like a problem with `ne_10m_lakes`

**Comment by pnorman** [comment]
z8 was a problem with a transient problem in OSM data sometime in the past which has been fixed, and errors in the code calling [`refresh.js`](https://github.com/CartoDB/CartoDB-basemaps/blob/d1c7c51de3728964667fc16c3f4ce3b2e22d59b7/data/refresh.js) were stopping it from correctly refreshing the materialized views on some servers. It happened on some tiles but not others because different servers were behaving differently.

I've manually refreshed and @zenitraM is fixing the script issue.

The problems on z7 seem to have gone away, please comment if you see them again after the next hour or so.
